-- دليل سلمية: قاعدة البيانات الأساسية
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text not null default '•',
  color text default '#087eea',
  sort_order int default 0,
  created_at timestamptz default now()
);

create table if not exists public.shops (
  id bigint generated by default as identity primary key,
  name text not null,
  category_id bigint references public.categories(id) on delete set null,
  phone text,
  address text,
  description text,
  slogan text,
  logo_url text,
  cover_url text,
  theme text default '#087eea',
  services jsonb default '[]'::jsonb,
  offers jsonb default '[]'::jsonb,
  gallery jsonb default '[]'::jsonb,
  hours text,
  maps_url text,
  rating numeric(2,1) default 0,
  reviews int default 0,
  is_featured boolean default false,
  created_at timestamptz default now()
);

alter table public.categories enable row level security;
alter table public.shops enable row level security;

-- القراءة العامة للموقع
create policy "public read categories" on public.categories for select using (true);
create policy "public read shops" on public.shops for select using (true);

-- ملاحظة: لا نفتح insert/update/delete للعامة.
-- إدارة المحلات يجب أن تتم عبر حساب Admin مصادق عليه أو Edge Function/Backend.
