-- دليل سلمية - جداول مستقلة عن أي جداول أخرى في المشروع
create table if not exists public.directory_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text not null default '📌',
  sort_order int default 0,
  created_at timestamptz default now()
);

create table if not exists public.directory_shops (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  phone text,
  whatsapp text,
  address text,
  description text,
  slogan text,
  logo_data text,
  cover_data text,
  theme text default '#087ee3',
  services jsonb default '[]'::jsonb,
  offers jsonb default '[]'::jsonb,
  gallery jsonb default '[]'::jsonb,
  hours jsonb default '{}'::jsonb,
  maps_url text,
  rating numeric(2,1) default 4.8,
  reviews int default 0,
  is_featured boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.directory_settings (
  id text primary key default 'main',
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now()
);

alter table public.directory_categories enable row level security;
alter table public.directory_shops enable row level security;
alter table public.directory_settings enable row level security;

-- الموقع يحتاج قراءة عامة، ولوحة الإدارة الحالية محمية برمز داخل الصفحة.
-- هذه الصلاحيات تجعل الحفظ يعمل من GitHub Pages باستخدام publishable key.
-- لاحقاً يمكن تشديدها باستخدام Supabase Auth.
drop policy if exists "directory categories public all" on public.directory_categories;
drop policy if exists "directory shops public all" on public.directory_shops;
drop policy if exists "directory settings public all" on public.directory_settings;
create policy "directory categories public all" on public.directory_categories for all to anon, authenticated using (true) with check (true);
create policy "directory shops public all" on public.directory_shops for all to anon, authenticated using (true) with check (true);
create policy "directory settings public all" on public.directory_settings for all to anon, authenticated using (true) with check (true);

insert into public.directory_categories(name,icon,sort_order) values
('أخرى','•••',1),('صيدليات','💊',2),('ألبسة وأحذية','👕',3),('منزل وأدوات','⌂',4),('مطاعم وكافيهات','🍴',5),('مواد غذائية','🛒',6),('اتصالات وإلكترونيات','📱',7),('تجميل وعناية','💇',8),('رياضة ولياقة','🏋',9)
on conflict (name) do nothing;
